package dev.jebaum.isometric.timer

import java.util.Locale
import org.junit.Assert.assertEquals
import org.junit.Assert.assertTrue
import org.junit.Test
import kotlin.math.abs

/**
 * Drives the Kotlin [Routine] through exactly the same deterministic script the
 * reference `timer.js` was driven through (see
 * `app/src/test/resources/js-reference-drive.txt`, generated by running the real
 * `timer.js` under Node), and diffs every snapshot field. Any behavioural
 * divergence in the port shows up as a line-by-line mismatch.
 */
class JsParityTest {

    private fun kindName(kind: Kind) = kind.name.lowercase()

    private fun drive(): List<String> {
        val lines = mutableListOf<String>()

        var time = 4223.456
        val routine = Routine(
            buildSchedule(Settings(cycles = 2, hold = 5, switch = 2, rest = 4)),
            now = { time },
        )

        fun record(tag: String) {
            val s = routine.snapshot()
            lines += listOf(
                tag,
                String.format(Locale.ROOT, "%.3f", time),
                s.phase.label,
                kindName(s.phase.kind),
                s.secondsLeft.toString(),
                String.format(Locale.ROOT, "%.6f", routine.progress().toDouble()),
                s.totalLeft.toString(),
                s.cycle.toString(),
                s.cycles.toString(),
                s.next,
                s.paused.toString(),
                s.started.toString(),
                s.done.toString(),
                clock(s.totalLeft),
            ).joinToString("|")
        }

        record("init")
        routine.togglePause()
        record("start")

        var step = 0
        while (step < 700) {
            time += 0.05
            step += 1
            if (step == 40) { routine.togglePause(); record("pause") }
            if (step == 60) { routine.togglePause(); record("resume") }
            if (step == 120) { routine.skip(); record("skip") }
            if (step == 121) { routine.skip(); record("skip2") }
            if (step % 7 == 0) record("t$step")
        }
        record("end")

        var t2 = 987654.321
        val r2 = Routine(
            buildSchedule(DEFAULT_SETTINGS),
            now = { t2 },
            startPaused = false,
        )
        for (i in 0 until r2.phases.size + 5) {
            t2 += 0.0166666
            r2.skip()
            val s = r2.snapshot()
            lines += listOf(
                "skipstorm",
                i.toString(),
                s.phase.label,
                s.secondsLeft.toString(),
                s.totalLeft.toString(),
                s.done.toString(),
                String.format(Locale.ROOT, "%.9f", r2.elapsed()),
            ).joinToString("|")
        }

        return lines
    }

    @Test
    fun `kotlin routine matches the javascript reference snapshot for snapshot`() {
        val expected = checkNotNull(
            javaClass.classLoader?.getResourceAsStream("js-reference-drive.txt"),
        ) { "js-reference-drive.txt missing from test resources" }
            .bufferedReader().readLines().filter { it.isNotBlank() }
        val actual = drive()

        assertEquals("line count", expected.size, actual.size)

        val mismatches = mutableListOf<String>()
        for (index in expected.indices) {
            val want = expected[index].split("|")
            val got = actual[index].split("|")
            if (want.size != got.size) {
                mismatches += "line $index arity: $want vs $got"
                continue
            }
            for (field in want.indices) {
                val a = want[field].toDoubleOrNull()
                val b = got[field].toDoubleOrNull()
                // progress is Double in JS and Float in Kotlin; compare numerics
                // with a tolerance wider than Float's precision.
                val same =
                    if (a != null && b != null) abs(a - b) <= 1e-5 else want[field] == got[field]
                if (!same) {
                    mismatches += "line $index field $field: expected '${want[field]}' " +
                        "got '${got[field]}' (${expected[index]} / ${actual[index]})"
                }
            }
        }
        assertTrue(mismatches.joinToString("\n"), mismatches.isEmpty())
    }
}
